### ISSUE TITLE
Reviewing: words of length beyond box size should wrap around

### ISSUE THREAD

**Issue by oliviabrown9** [TreeHacks/application-portal-frontend#11]
If a single word goes beyond the length of the box, instead of wrapping around, the word goes outside the box and increases the page width to fit. 
This is most commonly an issue with responses that include links.

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/20130899/50462876-be384000-094d-11e9-9b82-8106ab319041.png">

**Comment by epicfaace** [comment]
Fixed

![image](https://user-images.githubusercontent.com/1689183/50573514-6497a180-0da3-11e9-9aa7-e0a18fa96fe7.png)
