### ISSUE TITLE
Add different bus routes to admin view table

### ISSUE THREAD

**Issue by epicfaace** [TreeHacks/application-portal-frontend#15]
So that admins can view who has confirmed for different bus routes

**Comment by epicfaace** [comment]
Fixed

![image](https://user-images.githubusercontent.com/1689183/50573594-492d9600-0da5-11e9-8af8-a7b42a000f4d.png)

**Comment by epicfaace** [comment]
@oliviabrown9 this should be fixed now

**Comment by oliviabrown9** [comment]
@epicfaace Awesome, I'll check it out in next few days
